"""Updated complaints table

Revision ID: ac20c1e0a4c3
Revises: e61e736e4b31
Create Date: 2024-09-18 14:18:08.250607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac20c1e0a4c3'
down_revision: Union[str, None] = 'e61e736e4b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('complaints', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'reason',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('complaints', 'content')
    # ### end Alembic commands ###
