version: '3.8'

services:
  db:
    image: postgres:15
    container_name: articles_db
    env_file:
      - ./.env-non-dev
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: .
    container_name: articles_app
    env_file:
      - ./.env-non-dev
    depends_on:
      - db
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:
